version: 2
updates:
  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: weekly
    groups:
      pub-dependencies:
        patterns: ['*']
    commit-message:
      prefix: chore

  - package-ecosystem: bundler
    directory: /app
    schedule:
      interval: monthly
    groups:
      bundler-dependencies:
        patterns: ['*']
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directories:
      - /
      # Composite actions are not covered by the root directory scan
      - /.github/actions/*
    schedule:
      interval: monthly
    groups:
      github-actions-dependencies:
        patterns: ['*']
    commit-message:
      prefix: ci
